# Generated by Django 3.2.15 on 2022-09-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=80)),
                ('Site', models.CharField(max_length=80)),
                ('Date', models.DateTimeField()),
                ('White', models.CharField(max_length=80)),
                ('Black', models.CharField(max_length=80)),
                ('Result', models.CharField(max_length=20)),
                ('Termination', models.CharField(max_length=80)),
                ('Annotator', models.CharField(max_length=80)),
                ('Variant', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.IntegerField()),
                ('clockmove', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_db.game')),
            ],
        ),
    ]
