# Generated by Django 3.2.15 on 2022-09-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('game_id', 'ply')},
        ),
    ]
