# Generated by Django 3.2.15 on 2022-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0002_alter_move_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='TimeControl',
            field=models.CharField(default='300+0', max_length=40),
        ),
        migrations.AlterField(
            model_name='game',
            name='Variant',
            field=models.CharField(default='Standard', max_length=80),
        ),
    ]
